In [ ]:
import torch
print(torch.__version__)

In [ ]:
if torch.cuda.is_available():
  print("GPU is avaliable")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU not available. Using CPU


Creating Tensors

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1, 2, 3], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1, 2, 3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.rand_like(x, dtype = torch.float64)

tensor([[0.4037, 0.4141, 0.4705],
        [0.2825, 0.0047, 0.7970]], dtype=torch.float64)

In [4]:
import torch

x = torch.tensor(6.7)
y = torch.tensor(0.0)

#weight
w = torch.tensor(1.0)
#bias
b = torch.tensor(0.0)

In [3]:
def binary_cross_entropy_loss(prediction, target):
  epsilon = 1e-8
  prediction = torch.clamp(prediction, epsilon, 1-epsilon)
  return -(target * torch.log(prediction) + (1-target)*torch.log(1-prediction))

In [6]:
#forward pass
z = w * x + b
#applying sigmoid activation function
y_pred = torch.sigmoid(z)

#calculating loss using Binary Cross Entropy
loss = binary_cross_entropy_loss(y_pred, y)

In [7]:
loss

tensor(6.7012)

In [8]:
#dL/d(y_pred) : Loss w.r.t prediction
d_loss_dy_pred = (y_pred - y)/(y_pred * (1-y_pred))

#d(y_pred)/dz : Prediction w.r.t z (signmoid derivative)
dy_pred_dz = y_pred * (1-y_pred)

#dz/dw and dz/db : z w.r.t w and b
dz_dw = x
dz_db = 1

dL_dw = d_loss_dy_pred * dy_pred_dz * dz_dw
dL_db = d_loss_dy_pred * dy_pred_dz * dz_db

In [9]:
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t weight (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t weight (db): 0.998770534992218


In [10]:
#using autograd to calculate derivatives quickly
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [11]:
w = torch.tensor(1.0, requires_grad = True)
b = torch.tensor(0.0, requires_grad = True)

In [12]:
w

tensor(1., requires_grad=True)

In [13]:
b

tensor(0., requires_grad=True)

In [15]:
z = w * x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [16]:
y_pred = torch.sigmoid(z)

In [17]:
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [18]:
loss = binary_cross_entropy_loss(y_pred, y)

In [19]:
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [20]:
loss.backward()

In [25]:
w.grad

tensor(6.6918)

In [26]:
b.grad

tensor(0.9988)

In [28]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad = True)

In [29]:
x

tensor([1., 2., 3.], requires_grad=True)

In [30]:
y = (x**2).mean()

In [31]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [32]:
y.backward()

In [33]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [45]:
#clearing grad
x = torch.tensor(2.0, requires_grad = True)
x

tensor(2., requires_grad=True)

In [46]:
y = x ** 2

In [47]:
y

tensor(4., grad_fn=<PowBackward0>)

In [48]:
y.backward()

In [49]:
x.grad

tensor(4.)

In [51]:
x.grad.zero_()

tensor(0.)

In [52]:
x.requires_grad_(False)

tensor(2.)

In [54]:
x.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [55]:
x = torch.tensor(2.0, requires_grad = True)
x

tensor(2., requires_grad=True)

In [56]:
z = x.detach()

In [57]:
z

tensor(2.)

In [58]:
y = x ** 2

In [59]:
y.backward()

In [60]:
y1 = z ** 2

In [61]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [63]:
x.grad

tensor(4.)